# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faa52b8e9d01596387234cacf1b6a1ce123b0f312178d76773b941bcaf646046919fc9679e57ba4d09b7343aa1042cbac83fa284e237b193b6f69e4cd9dd93bb

test:
  secret_key_base: de472a1ad677eb88146a37a392e56cfce6c31529148bd40d7c4ea83b3e2787417892b8d605dbb314a58b788ad11d8232f2a0bdc7d7b0c34bbd4cd16a5498494f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
